Name:           ros-indigo-lama-test
Version:        0.1.2
Release:        0%{?dist}
Summary:        ROS lama_test package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/lama_test
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-dfs-explorer
Requires:       ros-indigo-lama-interfaces
Requires:       ros-indigo-lj-costmap
Requires:       ros-indigo-lj-laser-heading
Requires:       ros-indigo-local-map
Requires:       ros-indigo-nj-costmap
Requires:       ros-indigo-nj-escape-crossing
Requires:       ros-indigo-nj-laser
Requires:       ros-indigo-nj-oa-costmap
Requires:       ros-indigo-nj-oa-laser
Requires:       ros-indigo-pm-mcc
Requires:       ros-indigo-rviz
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-dfs-explorer
BuildRequires:  ros-indigo-lama-interfaces
BuildRequires:  ros-indigo-lj-costmap
BuildRequires:  ros-indigo-lj-laser-heading
BuildRequires:  ros-indigo-local-map
BuildRequires:  ros-indigo-nj-costmap
BuildRequires:  ros-indigo-nj-escape-crossing
BuildRequires:  ros-indigo-nj-laser
BuildRequires:  ros-indigo-nj-oa-costmap
BuildRequires:  ros-indigo-nj-oa-laser
BuildRequires:  ros-indigo-pm-mcc
BuildRequires:  ros-indigo-rviz

%description
The lama_test package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Jan 27 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.2-0
- Autogenerated by Bloom

